config/routes.rb
Rails.application.routes.draw do
  root to: 'products#index'
  resources :products do
    collection do
      get 'change_currency', to: 'products#change_currency', as: 'currency'
    end
  end

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/currency_detail.rb
# frozen_string_literal: true

class CurrencyDetail < ApplicationRecord
  serialize :details, Array
end

app/models/product.rb
# frozen_string_literal: true

class Product < ActiveRecord::Base
  require 'currency_data'

  def price
    price_in_cents / 100.0
  end

  def get_price(currency)
    c_price = show_price(currency)
    (price * c_price.to_f).round
  end

  def show_price(currency)
    c_data = CurrencyData.new
    c_data.get_currency_details(currency)
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def set_currencies
    c_data = CurrencyData.new
    @cash = c_data.get_currency_details
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  def index
    @products = Product.all
    set_currencies
  end

  def show
    @product = Product.find(params[:id])
  end

  def change_currency
    @product = Product.find(params[:id])
    @price = @product.get_price(params[:currency])
    @currency = params[:currency]
    render json: { price: @price, currency: @currency }
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price_in_cents)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
%head>
  %title 3scale marketplace
  = stylesheet_link_tag    'application', media: 'all'
  = javascript_include_tag 'application'
  = csrf_meta_tags

%body
  %main.container
    = yield

app/views/products/index.html.haml
%h1 Check out our products!

.row.product-list
  - @products.each do |product|
    %article.product
      %h2= product.name
      %p= product.description
      = select_tag :param_name,options_for_select([["EUR",product.price]]+@cash.map{|c| [c["currency"],c["rate"]]}),:onchange =>"select_currency(this,'#{product.id}')"

      %strong
        .price 
          = product.price
          EUR
      = link_to 'Show more', product

:javascript
  function select_currency(e,id) {  
    var rate = $(e).find('option:selected').text()
    console.log(rate)
    console.log(id)
    jQuery.ajax({
      url: "/products/change_currency",
      type: "GET",
      data: {"id" : id,"currency" : rate,},
      dataType: "html",
      success:function(data) {
        var data = JSON.parse(data)
       $(e).parent().find('.price').text(data.price + " " + data.currency)
       }
    });
  }

app/views/products/show.html.haml
%article.product
  %h1= @product.name

  %p= @product.description

  %strong
    = @product.price
    EUR

  = link_to 'Shut up and take my money!', '#'

= link_to 'Back to product list', products_path